language: python
python:
- '2.7'
install: pip install tox-travis
script: tox
addons:
  rethinkdb: '2.3'
env:
- HANDLE_COVERAGE=coveralls
deploy:
  provider: pypi
  username: dhozac
  password:
    secure: uQ+7G2bKqG3XW1SEPb9+LeduQ/JL7wkET967pu5b2RFzf109EQOQ5GEpkGzcBCYN0BkoHqTke277/KM0NxRwp1WGva4BdsnlLLW1xLQDse0+EuxZsA8GnH/J6sbYIiW7B9AKPlxSlFZ9chRLLtnIgxfTMlUSaTk7u7uh3M2lLgenF0I0U1Dsq+T6dho4DgoalOwDE98AZ+5d0cUhaM6GiTi+6lGJmqsekMYaRbB9heVerg/+LXbIW6humQsuoAodtyqL9EBrV5y9E++UJ0leTS9LJ+pQ7rQbPDKIxBZjOgToXHN/nnptq3E0xT9m5u140UHOCWYvUyv+ylFmM9HUzA2uP9eLTGs1YRWwCqSUY1YGPJWkgliCj5gZfv6U3jRI/geo0nIUNnzZgBdIGhhwcWbAWXhKGI/+h9ks3BjAsnFbfMrhRuPkkfL35aYb4JwJvedoDX8QlfgzFhN88DeE4/CrAWsl4dlUQbpgAd/W3IPNR3mvphXsI88ED69w5HwfxGkuBrZ4bjOhUFkHmSXiDAuwTC2shb5dCjPF6t9l2VqMmC49RKNKutq/T5d6TWDLPuzHLF4DLbjxuk+5+FpfE7BtYUClLgUdDbXHl8U7ktNgKMY+KI/Qv98bxoPn8gEfrrhbr8bPBlFaI+4n9HXjpxr9jb7eGKExFLQ/itdunLY=
  on:
    tags: true
